
:include("./defs.kql")

:setConnection({ type: "azureIdentity", cluster: "https://ddtelvscode.kusto.windows.net/" })
:setDefaultDb("VSCode")


let $event1 = RawEventsVSCode;

let $events = RawEventsVSCode
    | where EventName == "test";


# Query 123

:setOutput({ webEditorUrl: "https://test-viewer.de" })
:setOutput({ fileExt: ".test.json" })

$events
| where Properties["mode"] == "longterm" "5minWindow"

