
:setConnection({ type: "azureCli", cluster: "https://ddtelvscode.kusto.windows.net/" })
:setDefaultDb("VSCode")

:include("./vscode-events.kql")

// Show available edit detail sourcekeys by count
$events.editTelemetry.editSources.details
| take 10
| where BaseServerUploadTimestamp >= ago(1d)
| summarize Count = count() by Sourcekeycleaned
| order by Count desc
| take 50



RawEventsVSCode
| take 10
